### ISSUE TITLE
Naming issues / conflicts / duplicate services

### ISSUE THREAD

**Issue by LVerneyPEReN** [OpenTermsArchive/engine#439]
Hi,

It seems there are a few naming issues with the recent import of tosback data.

For instance, there is both a `Google Play` and a `Play` service which seems to identify the same actual service : https://github.com/ambanum/OpenTermsArchive/blob/master/services/Play.json vs https://github.com/ambanum/OpenTermsArchive/blob/master/services/Google%20Play.json.

Also, it is not clear to me what the correct naming should be for such services. Some are prefixed with the parent platform, some are not. For instance `Stadia` which I would have expected to be `Google Stadia` : https://github.com/ambanum/OpenTermsArchive/blob/master/services/Stadia.json.

Thanks!

**EDIT** Same for Alexa / Amazon Alexa

**Comment by LVerneyPEReN** [comment]
> We will probably organize a contribution evening in next november during the "Mois de l'innovation publique de la DITP", and it would be great to meet there?

Sure, let me know about it and happy to meet there!

**Comment by MattiSG** [comment]
The [documentation](https://docs.opentermsarchive.org/contributing-terms/) on how to name services can always be improved. Following https://github.com/OpenTermsArchive/engine/issues/995, it is in the [`docs` https://github.com/OpenTermsArchive/docs] repository 🙂 

A formal RFC for a naming scheme could also be accepted, if the problem statement can be refined 🙂 

As for the existing conflicts listed in this issue, they should be addressed directly in the [`contrib` collection](https://github.com/OpenTermsArchive/contrib-declarations/).

For triaging purposes, I close this issue as it stands since it does not reflect the current repository setup.
